[env:esp32-h2]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-h2-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 115200

board_build.partitions = zigbee.csv

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DZIGBEE_MODE_ZCZR
    -DCORE_DEBUG_LEVEL=3
    ; один датчик на шине -> поиск не нужен, экономим место
    -DCONFIG_SEARCH_ENABLED=0

; DallasTemperature НЕ используем - она тянет старую OneWire,
; которая не компилируется на H2. Берём драйвер DSTherm из OneWireNg.
lib_deps =
    https://github.com/pstolarz/OneWireNg.git

; страховка: если старая OneWire осталась в libdeps - игнорируем
lib_ignore =
    OneWire
    DallasTemperature
